# Mistral AI
MISTRAL_MODEL="ministral-8b-2410"
MISTRAL_API_KEY="xtyTZappMpsEpojjM1yhFsJrIngxW9gx"

# CODEGPT
CODEGPT_API_URL="https://api.codegpt.co/api/v1/"
CODEGPT_API_KEY="sk-86cefaae-f0fe-4634-b5ec-4c905a170ecb"